### ISSUE TITLE
Maintain list of bugs autotest2 helped to discover

### ISSUE THREAD

**Issue by mloskot** [schwehr/gdal-autotest2#4]
Not only interesting, but I think it would be a great if there was a log of bugs in GDAL, OGR and their dependencies discovered thanks to autotest2.

It would be an advantage to get the buy-in too.

@schwehr Do you plan to create such report? Or is there one already available?

**Comment by schwehr** [comment]
A lot of what I use autotest2 for is not to find gdal bugs: 

- prevent regressions coming from other libs, compilers, linkers, environment, hardware, etc.
- prevent / catch behavior changes in gdal
- make upgrading easier for those who can't easily automate / digest the output of tut or the autotest python

It is helpful to find bugs in these cases:

- Running asan, msan, ubsan, tsan, and other profilers against constrained and isolated cases with minimal overhead
- Running the llvm fuzzer or AFL on subparts of gdal.  e.g. using FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION and allowing junk directly into driver Open() calls

There isn't a report available, but it's a good idea.  e.g. I just submitted this:

https://trac.osgeo.org/gdal/changeset/37863

Created:

https://docs.google.com/spreadsheets/d/1gFEC94scVv7DfgELoYHEUChjx31eCZUqi019wqh008w/edit?usp=sharing

**Comment by mloskot** [comment]
The rationale certainly makes sense, but heavy(ier) and more detailed testing will certainly reveal issues, no doubt. So, I think it is a good idea to keep track of the autotest2 achievements.

A simple `BUGSTORY.md` would do too.
